version: '3.1'
services:
  app-be:
    image: 'backend-test:latest'
    ports:
      - "8080:8080"
    container_name: test-backend
    build:
      dockerfile: DockerFile
      context: ./backend-test
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sectors
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  app-fe:
    container_name: test-frontend
    image: 'frontend-test:latest'
    build:
      context: ./frontend-test
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - app-be

  db:
    image: 'postgres:latest'
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sectors
