FROM maven:latest AS maven-build
COPY . /test-backend
WORKDIR /test-backend
RUN mvn clean package -DskipTests

FROM openjdk:11
COPY --from=maven-build /test-backend/target/test-backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
